kimjang/mysite/urls.py
from django.contrib import admin
from django.urls import  path

from bookmark.views import BookmarkLV,BookmarkDV
import blog.views
import movie.views

from django.conf import settings
from django.conf.urls.static import static


app_name = 'bookmark'
urlpatterns = [
    path('admin/', admin.site.urls),
    #class-based views
    #path('bookmark/', BookmarkLV.as_view(), name='index'),
    #path('bookmark/<int:pk',BookmarkDV.as_view(), name='detail'),
    path('', blog.views.home, name = "home"),
    path('blog/<int:blog_id>', blog.views.detail, name= "detail"),

    #path('bookmark/', include('bookmark.urls')),
    path('blog/new/', blog.views.new, name="new"),
    path('blog/create/', blog.views.create, name="create"),
    path('blog/delete/<int:blog_id>', blog.views.delete, name="delete"),
    path('blog/edit/<int:blog_id>', blog.views.edit, name="edit"),
    path('blog/update/<int:blog_id>', blog.views.update, name="update"),
    path('blog/comment/<int:blog_id>', blog.views.add_comment_to_post, name="add_comment_to_post"),

    path('movie/',movie.views.movie, name="movie"),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kimjang/blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Hashtag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name
class Blog(models.Model):
    title = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    body = models.TextField()
    hashtag = models.ManyToManyField(Hashtag)

    def __str__(self):
        return self.title

    def summary(self):
        return self.body[:30]

class Comment(models.Model):
    post=models.ForeignKey(Blog, related_name='comments', on_delete=models.CASCADE)
    author_name=models.CharField(max_length=200)
    comment_text=models.TextField()
    created_at=models.DateTimeField(default=timezone.now)

    def approve(self):
        self.save()

    def __str__(self):
        return self.comment_text

kimjang/bookmark/models.py
from django.db import models

# Create your models here.

class Bookmark(models.Model) : 
    title = models.CharField('Title', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)

    def __str__(self) : 
        return self.title

kimjang/movie/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title=models.CharField(max_length=255)
    image=models.ImageField(upload_to='images/')
    description=models.CharField(max_length=500)

    def __str__(self):
        return self.title

kimjang/polls/models.py
from django.db import models

# Create your models here.

kimjang/blog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model=Comment
        fields=('author_name', 'comment_text')

kimjang/blog/views.py
from django.shortcuts import render, get_object_or_404,redirect
from .models import Blog
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from .forms import CommentForm

from blog.models import Blog, Hashtag
# Create your views here.
def home(request):
    blogs = Blog.objects
    return render(request, 'home.html', {'blogs':blogs})

def detail(request, blog_id):
    blog_detail = get_object_or_404(Blog, pk=blog_id)
    hashtags = blog_detail.hashtag.all()
    return render(request, 'detail.html', {'blog' : blog_detail, 'hashtags':hashtags})

def new(request):
    return render(request, 'new.html')
    
def create(request):
    blog = Blog()
    blog.title = request.GET['title']
    blog.body = request.GET['body']
    blog.pub_date = timezone.datetime.now()
    blog.save()

    hashtags=request.GET['hashtags']
    hashtag=hashtags.split(",")
    for tag in hashtag:
        ht=Hashtag.objects.get_or_create(name=tag)
        blog.hashtag.add(ht[0])
    return redirect('/blog/' + str(blog.id))

def delete(request, blog_id):
    blog = Blog.objects.get(pk=blog_id)
    blog.delete()
    return redirect('home')

def edit(request, blog_id):
    blog_edit = Blog.objects.get(pk= blog_id)
    return render(request, 'edit.html', {'blog': blog_edit})

@csrf_exempt
def update(request, blog_id):
    blog = Blog.objects.get(pk= blog_id)
    blog.title = request.POST['title']
    blog.body = request.POST['body']
    blog.pub_date = timezone.datetime.now()
    blog.save()
    return redirect('home')

def add_comment_to_post(request, blog_id):
    blog=get_object_or_404(Blog, pk=blog_id)
    if request.method=="POST":
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=blog
            comment.save()
            return redirect('detail', blog_id)
    else:
        form=CommentForm()
    return render(request, 'add_comment_to_post.html', {'form':form} )

kimjang/bookmark/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark

class BookmarkLV(ListView) : 
    models = Bookmark

class BookmarkDV(DetailView) : 
    model = Bookmark

kimjang/movie/views.py
from django.shortcuts import render
from .models import Movie

# Create your views here.
def movie(request):
    movies=Movie.objects
    return render(request, 'movie/movie.html',{'movies':movies})

kimjang/polls/views.py
from django.shortcuts import render

# Create your views here.

kimjang/blog/templates/add_comment_to_post.html
{% block comment %}
    <h1>새로운 댓글</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}
    

kimjang/blog/templates/detail.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg " style="background-color: rgb(61, 110, 73);">
<a class="navbar-brand" href="#" style="color: white; font-weight: bold; ">✨KIM&JANG✨</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}" style="color: white;">HOME </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}" style="color: rgba(255, 255, 255, 0.705);">돌아가기 </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'home' %}" style="color: rgba(255, 255, 255, 0.705);">돌아가기 </a>
      </li>

    </ul>
    <a class="btn btn-outline-light" href="{% url 'add_comment_to_post' blog.id %}" style='text-decoration: none;'>댓글쓰기</a>
  </div>
</nav>
<br>
<br>


<div class="container">
    <h1>✨{{ blog.title }}✨</h1>
    <p style="color: rgba(0, 0, 0, 0.562);">{{ blog.pub_date }}</p>
    <br>
    <p style="font-size:20px;">{{ blog.body }}</p>
    <br>
        <div class="hashtag" style="color: green">
            {% for hashtag in hashtags %}
             #{{hashtag.name}}
            {% endfor %}
        </div>
    <hr>
    {% for comment in blog.comments.all %}
        <div class='comment'>
            <strong>* {{ comment.author_name }}</strong>
            <div>{{ comment.comment_text|linebreaks }}</div>
            <div class="date" style="font-size:13px; color: rgba(0, 0, 0, 0.411);">{{ comment.created_at }}</div>
            <hr>
            
        </div>
    {% empty %}
        <p>. . . . . . 댓글이 아직 없네요 :(</p>
    {% endfor %}
    <br>
</div>

kimjang/blog/templates/edit.html
<div class="container">
    <form action="{% url 'update' blog.id %}" method="POST">
            {% csrf_token %}
        <h4>제목:</h4>
        <input type="text" name="title" value="{{blog.title}}">
        <br>
        <br>
        <h4>본문:</h4>
        <textarea cols=40 rows=10 name="body"> {{blog.body}} </textarea>
        <br>
        <br>
        <input class="btn btn-dark" type="submit" value="제출하기">
    </form>
</div>

kimjang/blog/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>김앤장의 떼껄룩</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <style>
      div, h1, h5, p, a { text-align: center;}
      .navbar{position: fixed; left:0; top:0; width: 100%; z-index:999;}
      .navbar-text{ margin-right: 100px;}
      h1{ font-weight: 900; margin-top: 50px;}
      .container{ text-align: left; display: grid; grid-template-columns: 1fr 1fr; margin: 30px auto 90px auto;}
      .card{ display: inline-block; margin: 30px 20px 0; padding: 30px ; width: 30rem;}
      footer{ position: fixed; left:0; bottom:0; width:100%; font-weight: 100; color: lightgray; margin-top: 10vh;}
      footer p{ font-size: 14px; font-weight: 500; padding: 15px 0 5px 0;}
    </style>
</head>

<body>
    <nav class="navbar navbar-expand-lg " style="background-color: rgb(61, 110, 73);">
    <a class="navbar-brand" href="#" style="color: white; font-weight: bold;">✨KIM&JANG✨</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}" style="color: white;">HOME <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movie' %}" style="color: white;">MOVIE<span class="sr-only">(current)</span></a>
      </li>
    </ul>
      <a class="btn btn-outline-light" href="{% url 'new' %}" style='text-decoration: none;'>글쓰기</a>
    </div>
    </nav>
    <br>
    <br>

  <h1><span style="font-weight: 600; font-size: 18px; color: black;">김앤장의</span><span style="color:rgb(7, 158, 88);"> 떼껄룩💚</span></h1>
  <h5 style="color: black;">💛기깔난 노래 취향에 대해 알아보아요💛</h5>

  <div class ="container">

  {% for blog in blogs.all %}
  <div class="card-group">
      <div class="card">
        <!-- <img src="{{movie.image.url}}" class="card-img-top" alt="음악 앨범"> -->
        <div class="card-body">
          <h5 class="card-title">✨{{ blog.title }}✨</h5>
          <!-- <p class="card-text">{{ blog.summary }}...</p> -->
          <p class="card-text"><small class="text-muted">{{ blog.pub_date }}</small></p>
          <a href="{% url 'detail' blog.id %}" class="btn btn-outline-success">보러갈래?</a>
          <a href="{% url 'edit' blog.id %}" class="btn btn-outline-success">수정할래?</a>
          <a href="{% url 'delete' blog.id %}" class="btn btn-outline-success">삭제할래?</a>
        </div>
      </div>
    </div>
  {% endfor %}
</div>

  <footer class="navbar-expand-lg navbar-dark bg-dark">
      <p>Copyright 2020.  &nbsp; 김앤장머리속 &nbsp;🧠 🧠 🧠 &nbsp; All Rights Reserved.</p>
  </footer>

</body>
</html>

kimjang/blog/templates/new.html
<div class="container">
    <form action="{% url 'create' %}">
        <h4>제목:</h4>
        <input type="text" name="title">
        <br>
        <br>
        <h4>본문:</h4>
        <textarea cols=40 rows=10 name="body"></textarea>
        <br>
        <br>
        <h4>해시태그 :  <input typ="text" name="hashtags" placeholder="해시태그(,로 구분)"></h4>
        <br>
        <input class="btn tn-dark" type="submit" value="제출하기">
    </form>
</div>

kimjang/bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark Detail</title>
</head>
<body>
    <div id="content">
        <h1>{{ odject.title }}</h1>
        <ul>
            <li>URL : <a href="{{ object.url }}">{{ object.url }}</a></li>
        </ul>
    </div>
</body>
</html>

kimjang/bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Bookmark</title>
</head>
<body>
    <div id="content">
        <h1>Bookmark List</h1>

        <ul>
            {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
            {% endfor %}
        </ul>
    </div>
</body>
</html>

kimjang/movie/templates/movie/movie.html
{%load static%}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<nav class="navbar navbar-expand-lg " style="background-color: rgb(61, 110, 73);">
  <a class="navbar-brand" href="#" style="color: white;">KIM&JANG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'home' %}" style="color: white;">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'movie' %}" style="color: white;">Movie<span class="sr-only">(current)</span></a>
      </li>
    </ul> 
  </div>
  </nav>
  </head>

  <body>
    <main role="main">


      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                <img src="{%static 'harrypotter1.jpg' %}" height="400" alt="해리포터1 포스터">
                <div class="card-body">
                  <p class="card-text"> 해리는 볼드모트로부터 마법의 돌과 호그와트 마법학교를 지키기 위해 필사의 노력을 하는데...</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                      <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                    </div>
                    <small class="text-muted">9 mins</small>
                  </div>
                </div>
              </div>
            </div>

            {%for movie in movies.all%}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                  <img src="{{movie.image.url}}" height="400" alt="영화 포스터">
                  <div class="card-body">
                    <p class="card-text">{{movie.description}}</p>
                    <div class="d-flex justify-content-between align-items-center">
                      <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                      </div>
                      <small class="text-muted">9 mins</small>
                    </div>
                  </div>
                </div>
              </div>
              {%endfor%}
          </div>
        </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container">
        <p class="float-right">
          <a href="#">Back to top</a>
        </p>
        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>
        <p>New to Bootstrap? <a href="../../">Visit the homepage</a> or read our <a href="../../getting-started/">getting started guide</a>.</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
  </body>
</html>